data:
  features_path: "data/processed/features.csv"
  
model:
  name: "random_forest"
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  param_grid:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 20]
    min_samples_split: [2, 5, 10]
  save_path: "models/best_model.pkl"
  
training:
  test_size: 0.2
  random_state: 42
  cv_folds: 5
  hyperparameter_tuning: true
  
evaluation:
  metrics: ["accuracy", "f1", "precision", "recall"]
  output_dir: "results/"
